---
- name: 'Laboratorio de variables'
  hosts: nodos
  vars_files:
    'vars/default.yml'
  vars:
    grupos:
      - ctic
      - devops
      - everis

  tasks:
    - name: 'Instala los paquetes correspondientes a los servicios en vars/default.yml'
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - openssh-server
        - firewalld
        - httpd
        - mariadb-server

    - name: 'Arranca los servicios'
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop: "{{ servicios }}"
    
    - name: 'Crea los grupos'
      group:
        name: "{{ item }}"
        state: present
      loop: "{{ grupos }}"

    - name: 'Crea el usuario administrador'
      vars:
        usuario: "administrador"
      user:
        name: '{{ usuario }}'
        group: '{{ usuarios[usuario]["grupo"] }}'
        generate_ssh_key: '{{ usuarios[usuario]["generar_key"] }}'
        ssh_key_file: '{{ usuarios[usuario]["ruta_key"] }}'
        expires: '{{ usuarios[usuario]["expira"] }}'

    - name: 'Crea el usuario everis_pruebas'
      vars:
        usuario: "everis_pruebas"
      user:
        name: '{{ usuario }}'
        group: '{{ usuarios[usuario]["grupo"] }}'
        generate_ssh_key: '{{ usuarios[usuario]["generar_key"] }}'
        uid: '{{ usuarios[usuario]["uid"] }}' 
        expires: '{{ usuarios[usuario]["expira"] }}'

    - name: 'Crea el usuario nuestro'
      vars:
        usuario: "nuestro"
      user:
        name: '{{ usuario }}'
        groups: '{{ usuarios[usuario]["grupo"] }}'
        append: yes
        generate_ssh_key: '{{ usuarios[usuario]["generar_key"] }}'
        ssh_key_file: '{{ usuarios[usuario]["ruta_key"] }}'
        expires: '{{ usuarios[usuario]["expira"] }}'

    - name: 'Reinicia los servicios'
      systemd:
        name: "{{ item }}"
        state: restarted
      loop: "{{ servicios }}"

    - name: 'Reinicia los nodos'
      reboot:
...