---
servicios:
  - sshd
  - firewalld
  - httpd
  - mariadb
  # El servicio es mariadb, no mariadb-server. Cambiamos el enunciado para que funcione:

usuarios:
  administrador:
    grupo: root
    generar_key: yes
    ruta_key: .ssh/id_rsa
    expira: -1
  everis_pruebas:
    grupo: everis
    generar_key: no
    uid: 1212
    expira: 12407987
  nuestro:
    grupo: ctic, devops
    generar_key: yes
    ruta_key: .ssh/id_rsa
    expira: 122403387
...