---
servicios:
  # - sshd: no funciona porque el nombre del servicio no coincide con el nombre del paquete a instalar
  # Paquete: openssh-server
  # Servicio: sshd
  - firewalld
  - httpd
  # Paquete: - mariadb-server
  # Servicio: mariadb.service

usuarios:
  administrador:
    grupo: root
    generar_key: yes
    ruta_key: .ssh/id_rsa
    expira: -1
  everis_pruebas:
    grupo: everis
    generar_key: no
    # uid: 1212 : falta el ruta key y sobre el UID
    expira: 12407987
  nuestro:
    grupo: "ctic, devops"
    generar_key: yes
    ruta_key: .ssh/id_rsa
    expira: 122403387
...